# Generated by Django 2.1.4 on 2018-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181227_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user_comment',
            new_name='comment_user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
